"""NFE-015 — hard completion gate: regression suite against the thesis's
published 1h results table (da-tese-ao-produto.md section 1.3), run through
the REAL `run_validation_protocol` orchestrator (NFE-014), not through
metrics.py/dm_test.py directly.

============================== DISCLOSURE ==================================
1. The thesis's original 1h dataset and model-fitting scripts
   (`run_arima_returns.py`, `run_rf_noleak.py`, `run_sarima_only.py`) are NOT
   present anywhere in this repo (confirmed repo-wide search, see
   docs/tickets/NFE-015.md "Analysis"). `jupyter_notebooks/data/` has raw BTC
   OHLCV/sentiment/hash-rate CSVs, but not a ready-made reconstruction of the
   thesis's exact OLS/RF/ARIMA train/test scenario, fitted models, or
   per-split errors. Re-deriving that pipeline is out of scope for this
   library (it validates, it does not fit models) and out of scope for this
   ticket.

2. This suite therefore uses CHECKED-IN, DETERMINISTIC, SEEDED SYNTHETIC
   fixtures. `y_true` in every scenario below is calibrated (via
   `fixtures._calibrated_magnitudes`, an affine rescale of a seeded
   Gamma(0.8) sample) so that Naive0 -- whose forecast is always exactly
   zero -- reproduces the published Naive0 MAE/RMSE (0.003627/0.005321)
   exactly (to float64 rounding) in every run below. OLS/RF/ARIMA are NOT
   fitted models here: they are synthetic forecast series, produced by
   `_SyntheticForecast`-family `Baseline` implementations that look up a
   precomputed, calibrated prediction for each split's test window by index,
   calibrated so the resulting `MetricSet`/`DMResult` that `metrics.py`/
   `dm_test.py` (invoked *by* `run_validation_protocol`, not by this file
   directly) compute reproduce the published numbers within documented
   tolerance.

3. What is, and is not, verified end-to-end via `run_validation_protocol` in
   this file:
     - Naive0 MAE/RMSE (1h): reproduced end-to-end, in every scenario below
       (it is recomputed by the orchestrator itself every run since it is a
       mandatory baseline), tolerance 1e-6 (exact by construction, float
       rounding only).
     - OLS MAE/RMSE, RF MAE/RMSE, ARIMA MAE/RMSE (1h): each reproduced
       end-to-end, tolerance 1e-6.
     - OLS DA/F1, RF DA/F1, ARIMA DA/F1 (1h): each reproduced end-to-end.
       DA tolerance 1e-6 (exact -- n=10000 chosen so n*DA/100 is an integer
       for all three published DA figures). F1 tolerance 2.5e-4 (the
       quadrant-count solution for TP/TN is not integer in general and must
       be rounded to the nearest whole point; this is the resulting,
       empirically small, rounding error -- see fixtures.py's directional
       scenario comment for the derivation).
     - IMPORTANT CAVEAT, stated plainly: for each model, MAE/RMSE and DA/F1
       are verified in TWO SEPARATE `run_validation_protocol` calls, each on
       its own calibrated series, not jointly on one series in one run. No
       closed-form single-series construction was found (within this
       ticket's effort) that pins mean-absolute-residual, root-mean-square-
       residual, and two independent sign-quadrant counts simultaneously --
       that is a strictly harder joint-calibration problem than any of the
       four individually. Every number is still produced by a real call to
       `run_validation_protocol`; it is only the "all five numbers from one
       split" framing of the published table row that this suite does not
       attempt.
     - OLS DM verdict count (1h, published 0 better / 4 worse): reproduced
       end-to-end, across 4 real splits generated by `run_validation_protocol`
       (not by calling `dm_test` directly) -- see `test_ols_dm_end_to_end`.
       This reuses `fixtures.build_ols_dm_splits_1h`'s per-split error
       construction (NFE-011), replayed through the real split/baseline/DM
       pipeline instead of calling `dm_test` on the errors by hand.
     - RF DM verdict count (published 0/13) and ARIMA DM verdict count
       (published 0/53) are NOT reproduced anywhere in this repo, end-to-end
       or at the function level. `fixtures.py` (NFE-011) explicitly scoped
       these out for the same reason repeated here: no RF- or ARIMA-shaped
       per-split error fixture exists, and inventing 13 (or 53) independent
       synthetic splits from nothing but a single published aggregate
       MAE/RMSE row is a materially bigger, separately-scoped undertaking.
       Per this ticket's own acceptance criteria, one full B/W pair
       reproduced end-to-end (OLS, above) satisfies the DM requirement; RF's
       and ARIMA's B/W *counts* are the one line of the published table this
       suite does not claim to reproduce, anywhere.

4. This is a DISCLOSED DOWNGRADE from full reproduction of the thesis's
   pipeline to synthetic, fixture-based reconstruction of its published
   *numbers* -- stated here, at the top of the file that a Tech Lead or
   future maintainer will actually open, not buried in a ticket or commit
   message.
==============================================================================

Where fixture code lives: the shared 1h Naive0/OLS magnitude fixture and the
OLS DA/F1 and DM fixtures already exist in tests/fixtures.py (NFE-005/009/011)
and are imported here rather than rebuilt. The RF/ARIMA scenarios and the
"replay a calibrated series through the real orchestrator" plumbing
(`_with_preamble`, `_SyntheticForecast` family) are new and specific to this
ticket's full-pipeline reconstruction, so they live in this file rather than
in fixtures.py, per the ticket's Design section ("your call, document which
you chose").
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from naive_first_engine.protocol import NAIVE0_KEY, ValidationConfig, run_validation_protocol

from . import fixtures
from .fixtures import (
    DIRECTIONAL_TOLERANCE_DA,
    DIRECTIONAL_TOLERANCE_F1,
    NAIVE0_MAE_1H,
    NAIVE0_RMSE_1H,
    OLS_DA_1H,
    OLS_F1_1H,
    OLS_MAE_1H,
    OLS_RMSE_1H,
    TOLERANCE,
    build_1h_reference_scenario,
    build_directional_reference_scenario_1h,
    build_ols_dm_splits_1h,
)

# Published 1h numbers not already exported by fixtures.py, da-tese-ao-
# produto.md section 1.3.
RF_MAE_1H = 0.004033
RF_RMSE_1H = 0.005692
RF_DA_1H = 51.12
RF_F1_1H = 0.427
ARIMA_MAE_1H = 0.045971
ARIMA_RMSE_1H = 0.051331
ARIMA_DA_1H = 50.27
ARIMA_F1_1H = 0.488

# Quadrant counts (TP/TN/FP/FN, n=10000) solving the DA/F1 equations from
# fixtures.py's directional-scenario comment for the RF/ARIMA targets above,
# rounded to the nearest integer point (same method as fixtures.py's
# _DIR_COUNTS_1H/_DIR_COUNTS_6H). Verified empirically (scratch calc, not
# checked in) that both rounded solutions reproduce DA exactly and F1 to
# within DIRECTIONAL_TOLERANCE_F1.
_RF_DIR_COUNTS = {"TP": 1821, "TN": 3291, "FP": 1709, "FN": 3179}
_ARIMA_DIR_COUNTS = {"TP": 2370, "TN": 2657, "FP": 2343, "FN": 2630}

_PREAMBLE_LEN = 50
_PURGE_GAP = 24  # thesis default (da-tese-ao-produto.md section 1.2): 24h purge gap.


def _with_preamble(target: pd.Series, seed: int) -> pd.Series:
    """Prepend `_PREAMBLE_LEN + _PURGE_GAP` filler points before `target` so a
    single-split `ValidationConfig(train_window=_PREAMBLE_LEN, ...,
    purge_gap=_PURGE_GAP)` run's ONE split covers exactly `train=filler`,
    `test=target` -- i.e. `target`'s values are what the real orchestrator
    scores, not a hand-picked subset. Filler values are tiny seeded noise
    (not a flat constant) purely so `metrics.mase`'s in-sample seasonal-naive
    denominator isn't a division-by-zero on a constant train segment; no
    assertion in this file depends on the filler's actual values, Naive0
    ignores `train` entirely, and the synthetic-forecast baselines below look
    up their prediction by index rather than reading `train`.
    """
    filler_n = _PREAMBLE_LEN + _PURGE_GAP
    filler_index = pd.date_range(
        end=target.index[0] - pd.Timedelta(hours=1), periods=filler_n, freq="h"
    )
    filler = pd.Series(
        np.random.default_rng(seed).normal(0.0, 1e-6, size=filler_n), index=filler_index
    )
    return pd.concat([filler, target])


def _single_split_config(target_len: int, extra_baselines: list) -> ValidationConfig:
    return ValidationConfig(
        train_window=_PREAMBLE_LEN,
        test_window=target_len,
        step=target_len,
        purge_gap=_PURGE_GAP,
        horizon=1,
        extra_baselines=extra_baselines,
    )


class _SyntheticForecast:
    """Looks up a precomputed, calibrated forecast for the split's test
    window by index rather than fitting a model -- see module disclosure
    point 2. Structurally satisfies the `Baseline` protocol.
    """

    def __init__(self, y_pred: pd.Series) -> None:
        self._y_pred = y_pred

    def predict(self, train: pd.Series, test: pd.Series) -> pd.Series:
        return self._y_pred.loc[test.index]


class _SyntheticOLS(_SyntheticForecast):
    pass


class _SyntheticRF(_SyntheticForecast):
    pass


class _SyntheticARIMA(_SyntheticForecast):
    pass


def _assert_naive0(baseline_results) -> None:
    m = baseline_results[NAIVE0_KEY].metrics
    assert m.mae == pytest.approx(NAIVE0_MAE_1H, abs=TOLERANCE)
    assert m.rmse == pytest.approx(NAIVE0_RMSE_1H, abs=TOLERANCE)


def _build_model_mae_rmse_scenario(
    seed_true_magnitude: int,
    seed_true_sign: int,
    seed_resid_magnitude: int,
    seed_resid_sign: int,
    model_mae: float,
    model_rmse: float,
    index: pd.DatetimeIndex,
) -> tuple[pd.Series, pd.Series]:
    """Generalizes `fixtures.build_1h_reference_scenario`'s OLS construction
    (Naive0-calibrated y_true, independently-calibrated residual, signed) to
    an arbitrary target (mae, rmse) pair, reusing fixtures.py's private
    calibration primitives rather than re-deriving the affine-rescale math.
    """
    true_magnitude = fixtures._calibrated_magnitudes(
        seed_true_magnitude, NAIVE0_MAE_1H, NAIVE0_RMSE_1H
    )
    y_true = pd.Series(
        fixtures._signed(true_magnitude, seed_true_sign), index=index, name="y_true"
    )
    resid_magnitude = fixtures._calibrated_magnitudes(
        seed_resid_magnitude, model_mae, model_rmse
    )
    resid = pd.Series(fixtures._signed(resid_magnitude, seed_resid_sign), index=index)
    y_pred = (y_true - resid).rename("y_pred")
    return y_true, y_pred


# ---------------------------------------------------------------------------
# Naive0 / OLS MAE, RMSE -- reuses fixtures.build_1h_reference_scenario as-is.


def test_naive0_and_ols_mae_rmse_end_to_end():
    scenario = build_1h_reference_scenario()
    series = _with_preamble(scenario.y_true, seed=1)
    baseline = _SyntheticOLS(scenario.y_pred_ols)
    config = _single_split_config(len(scenario.y_true), [baseline])

    results = run_validation_protocol(series, config)

    assert len(results) == 1
    baseline_results = results[0].baseline_results
    _assert_naive0(baseline_results)

    ols_metrics = baseline_results["_SyntheticOLS"].metrics
    assert ols_metrics.mae == pytest.approx(OLS_MAE_1H, abs=TOLERANCE)
    assert ols_metrics.rmse == pytest.approx(OLS_RMSE_1H, abs=TOLERANCE)


# ---------------------------------------------------------------------------
# OLS DA / F1 -- reuses fixtures.build_directional_reference_scenario_1h.


def test_ols_da_f1_end_to_end():
    scenario = build_directional_reference_scenario_1h()
    series = _with_preamble(scenario.y_true, seed=2)
    baseline = _SyntheticOLS(scenario.y_pred_ols)
    config = _single_split_config(len(scenario.y_true), [baseline])

    results = run_validation_protocol(series, config)

    assert len(results) == 1
    ols_metrics = results[0].baseline_results["_SyntheticOLS"].metrics
    assert ols_metrics.da == pytest.approx(OLS_DA_1H, abs=DIRECTIONAL_TOLERANCE_DA)
    assert ols_metrics.f1 == pytest.approx(OLS_F1_1H, abs=DIRECTIONAL_TOLERANCE_F1)


# ---------------------------------------------------------------------------
# OLS DM verdict count (published 0 better / 4 worse) -- replays
# fixtures.build_ols_dm_splits_1h's 4 per-split error pairs through the real
# splitter/baseline/DM pipeline instead of calling dm_test() by hand.


def _build_ols_dm_series() -> tuple[pd.Series, pd.Series]:
    chunks = build_ols_dm_splits_1h()
    test_w = len(chunks[0].errors_naive0)
    step = _PREAMBLE_LEN + _PURGE_GAP + test_w
    total_n = (len(chunks) - 1) * step + _PREAMBLE_LEN + _PURGE_GAP + test_w

    index = pd.date_range("2020-01-01", periods=total_n, freq="h")
    y_true = pd.Series(
        np.random.default_rng(3).normal(0.0, 1e-6, size=total_n), index=index
    )
    y_pred = y_true.copy()

    for k, chunk in enumerate(chunks):
        test_start_pos = k * step + _PREAMBLE_LEN + _PURGE_GAP
        idx_slice = index[test_start_pos : test_start_pos + test_w]
        # Naive0's forecast is always exactly 0, so errors_naive0 IS y_true on
        # this slice; y_pred is back-derived so that test - y_pred reproduces
        # errors_model exactly once the orchestrator recomputes it.
        errors_naive0 = chunk.errors_naive0.to_numpy()
        errors_model = chunk.errors_model.to_numpy()
        y_true.loc[idx_slice] = errors_naive0
        y_pred.loc[idx_slice] = errors_naive0 - errors_model

    return y_true, y_pred


def test_ols_dm_end_to_end():
    y_true, y_pred = _build_ols_dm_series()
    chunks = build_ols_dm_splits_1h()
    test_w = len(chunks[0].errors_naive0)
    step = _PREAMBLE_LEN + _PURGE_GAP + test_w
    config = ValidationConfig(
        train_window=_PREAMBLE_LEN,
        test_window=test_w,
        step=step,
        purge_gap=_PURGE_GAP,
        horizon=1,
        extra_baselines=[_SyntheticOLS(y_pred)],
    )

    results = run_validation_protocol(y_true, config)

    assert len(results) == len(chunks) == 4
    verdicts = [r.baseline_results["_SyntheticOLS"].dm_result.verdict for r in results]
    assert verdicts == ["worse"] * 4  # published: 0 better / 4 worse


# ---------------------------------------------------------------------------
# RF MAE / RMSE, DA / F1 -- new synthetic scenarios (no prior RF fixture
# existed), built with the same techniques as the OLS ones above.


def test_rf_mae_rmse_end_to_end():
    index = pd.date_range("2022-01-01", periods=2000, freq="h", name="timestamp")
    y_true, y_pred = _build_model_mae_rmse_scenario(
        seed_true_magnitude=500,
        seed_true_sign=1500,
        seed_resid_magnitude=501,
        seed_resid_sign=1501,
        model_mae=RF_MAE_1H,
        model_rmse=RF_RMSE_1H,
        index=index,
    )
    series = _with_preamble(y_true, seed=4)
    baseline = _SyntheticRF(y_pred)
    config = _single_split_config(len(y_true), [baseline])

    results = run_validation_protocol(series, config)

    assert len(results) == 1
    baseline_results = results[0].baseline_results
    _assert_naive0(baseline_results)
    rf_metrics = baseline_results["_SyntheticRF"].metrics
    assert rf_metrics.mae == pytest.approx(RF_MAE_1H, abs=TOLERANCE)
    assert rf_metrics.rmse == pytest.approx(RF_RMSE_1H, abs=TOLERANCE)


def test_rf_da_f1_end_to_end():
    scenario = fixtures._build_directional_scenario(
        _RF_DIR_COUNTS, seed_shuffle=5510, seed_true_magnitude=5511, seed_pred_magnitude=5512
    )
    series = _with_preamble(scenario.y_true, seed=5)
    baseline = _SyntheticRF(scenario.y_pred_ols)  # field name is generic; holds the RF forecast here
    config = _single_split_config(len(scenario.y_true), [baseline])

    results = run_validation_protocol(series, config)

    assert len(results) == 1
    rf_metrics = results[0].baseline_results["_SyntheticRF"].metrics
    assert rf_metrics.da == pytest.approx(RF_DA_1H, abs=DIRECTIONAL_TOLERANCE_DA)
    assert rf_metrics.f1 == pytest.approx(RF_F1_1H, abs=DIRECTIONAL_TOLERANCE_F1)


# ---------------------------------------------------------------------------
# ARIMA MAE / RMSE, DA / F1 -- same techniques again; ARIMA's much larger
# published error (~13x Naive0's) makes this construction easier than RF/OLS,
# not harder: see _build_model_mae_rmse_scenario, which has no trouble
# finding a valid affine calibration at this scale.


def test_arima_mae_rmse_end_to_end():
    index = pd.date_range("2023-01-01", periods=2000, freq="h", name="timestamp")
    y_true, y_pred = _build_model_mae_rmse_scenario(
        seed_true_magnitude=502,
        seed_true_sign=1502,
        seed_resid_magnitude=503,
        seed_resid_sign=1503,
        model_mae=ARIMA_MAE_1H,
        model_rmse=ARIMA_RMSE_1H,
        index=index,
    )
    series = _with_preamble(y_true, seed=6)
    baseline = _SyntheticARIMA(y_pred)
    config = _single_split_config(len(y_true), [baseline])

    results = run_validation_protocol(series, config)

    assert len(results) == 1
    baseline_results = results[0].baseline_results
    _assert_naive0(baseline_results)
    arima_metrics = baseline_results["_SyntheticARIMA"].metrics
    assert arima_metrics.mae == pytest.approx(ARIMA_MAE_1H, abs=TOLERANCE)
    assert arima_metrics.rmse == pytest.approx(ARIMA_RMSE_1H, abs=TOLERANCE)


def test_arima_da_f1_end_to_end():
    scenario = fixtures._build_directional_scenario(
        _ARIMA_DIR_COUNTS, seed_shuffle=6610, seed_true_magnitude=6611, seed_pred_magnitude=6612
    )
    series = _with_preamble(scenario.y_true, seed=7)
    baseline = _SyntheticARIMA(scenario.y_pred_ols)  # field name is generic; holds the ARIMA forecast here
    config = _single_split_config(len(scenario.y_true), [baseline])

    results = run_validation_protocol(series, config)

    assert len(results) == 1
    arima_metrics = results[0].baseline_results["_SyntheticARIMA"].metrics
    assert arima_metrics.da == pytest.approx(ARIMA_DA_1H, abs=DIRECTIONAL_TOLERANCE_DA)
    assert arima_metrics.f1 == pytest.approx(ARIMA_F1_1H, abs=DIRECTIONAL_TOLERANCE_F1)
