"""NFE-016 — regression suite against the thesis's published 24h results
table (da-tese-ao-produto.md section 1.3), run through the REAL
`run_validation_protocol` orchestrator (NFE-014). See test_regression_6h.py
for the sibling 6h suite (near-identical structure, different horizon and
published targets) and its module docstring for the fuller rationale this
file mirrors.

============================== DISCLOSURE ==================================
1. The thesis's original 24h dataset and model-fitting scripts
   (`run_arima_returns.py`, `run_rf_noleak.py`, `run_sarima_only.py`) are NOT
   present anywhere in this repo -- same confirmed absence as NFE-015/
   NFE-016's 6h suite (docs/tickets/NFE-015.md, NFE-016.md "Analysis"). No
   new data has been added since.

2. This suite uses CHECKED-IN, DETERMINISTIC, SEEDED SYNTHETIC fixtures,
   built with the same techniques as test_regression_1h.py/test_regression_
   6h.py. The published 24h table (da-tese-ao-produto.md section 1.3) has NO
   RMSE column -- only MAE, DA, F1, DM(B/W), same as 6h. Calibration here
   pins ONLY the target mean (MAE), via `_calibrated_magnitude_mean_only`
   (a single-parameter positive rescale) -- there is no second (RMSE) target
   to solve for, and inventing one would misrepresent the source. No RMSE
   assertion appears anywhere in this file.

3. What is, and is not, verified end-to-end via `run_validation_protocol` in
   this file:
     - Naive0 MAE (24h): reproduced end-to-end in every scenario below,
       tolerance 1e-6 (exact by construction, float rounding only).
     - OLS MAE, RF MAE (24h): each reproduced end-to-end, tolerance 1e-6.
     - OLS DA/F1, RF DA/F1 (24h): each reproduced end-to-end. DA tolerance
       1e-6 (exact -- n=10000 chosen so n*DA/100 is an integer for both
       published DA figures, same method as fixtures.py's directional
       scenarios). F1 tolerance 2.5e-4 (quadrant-count rounding).
     - Same caveat as the 1h/6h suites: MAE and DA/F1 are verified in
       separate `run_validation_protocol` calls per model, not jointly on
       one series in one run.
     - OLS DM verdict count (24h, published 14 better / 22 worse):
       reproduced end-to-end across 36 real splits generated by
       `run_validation_protocol` (not by calling `dm_test` directly) -- see
       `test_ols_dm_end_to_end`.
     - RF DM verdict count (published 7/34) is NOT reproduced anywhere in
       this file, end-to-end or at the function level. Per this ticket's
       acceptance criteria, one full B/W pair reproduced end-to-end (OLS,
       above) satisfies the DM requirement; RF's B/W *count* is the one line
       of the published 24h table this suite does not claim to reproduce.
     - Harvey correction (horizon=24 vs horizon=1, same per-split error
       arrays): demonstrated via a DIRECT `dm_test.dm_test(...)` call in
       `test_harvey_correction_changes_statistic_at_24h` -- this is the one
       assertion in this file that does NOT go through
       `run_validation_protocol` (see docs/tickets/NFE-016.md "Design").

4. This is a DISCLOSED DOWNGRADE from full reproduction of the thesis's
   pipeline to synthetic, fixture-based reconstruction of its published
   *numbers* -- stated here, at the top of the file, not buried in a ticket
   or commit message.
==============================================================================

Where fixture code lives: `fixtures.py`'s generic directional
(`_build_directional_scenario`) and sign (`_signed`) primitives are reused
as-is (NFE-005/009/011) -- there is no 24h-specific directional fixture in
fixtures.py to reuse wholesale (unlike 6h's `build_directional_reference_
scenario_6h`), so this file supplies its own 24h quadrant counts, same
method as fixtures.py's own 1h/6h ones. The MAE-only calibration, DM-split,
and Harvey-correction-demo plumbing duplicate test_regression_6h.py's
(documented, accepted per-horizon-file duplication -- see that file's
docstring and docs/tickets/NFE-016.md "Design").
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from naive_first_engine import dm_test as dm_test_module
from naive_first_engine.protocol import NAIVE0_KEY, ValidationConfig, run_validation_protocol

from . import fixtures
from .fixtures import DIRECTIONAL_TOLERANCE_DA, DIRECTIONAL_TOLERANCE_F1, TOLERANCE

# Published 24h numbers, da-tese-ao-produto.md section 1.3 (no RMSE column at
# this horizon -- confirmed by direct re-read, per this ticket's Analysis).
NAIVE0_MAE_24H = 0.019720
OLS_MAE_24H = 0.020895
OLS_DA_24H = 50.80
OLS_F1_24H = 0.524
RF_MAE_24H = 0.029491
RF_DA_24H = 49.48
RF_F1_24H = 0.462

# Quadrant counts (TP/TN/FP/FN, n=10000) solving the DA/F1 equations from
# fixtures.py's directional-scenario comment for the OLS/RF 24h targets
# above, rounded to the nearest integer point (same method as fixtures.py's
# _DIR_COUNTS_1H/_DIR_COUNTS_6H). Verified empirically (scratch calc, not
# checked in) that both rounded solutions reproduce DA exactly and F1 to
# within DIRECTIONAL_TOLERANCE_F1 (~6e-6 and ~9e-5 respectively).
_OLS_DIR_COUNTS_24H = {"TP": 2708, "TN": 2372, "FP": 2628, "FN": 2292}
_RF_DIR_COUNTS_24H = {"TP": 2169, "TN": 2779, "FP": 2221, "FN": 2831}

_GAMMA_SHAPE = 0.8
_N = 2000
_PREAMBLE_LEN = 50
_PURGE_GAP = 24  # thesis default (da-tese-ao-produto.md section 1.2): 24h purge gap, independent of horizon.
_HORIZON = 24


def _with_preamble(target: pd.Series, seed: int) -> pd.Series:
    """Identical construction to test_regression_1h.py's `_with_preamble` --
    see that file for the full rationale. Duplicated here rather than
    imported per the ticket's Design section (minor duplication across the
    per-horizon regression files is an accepted, documented trade-off).
    """
    filler_n = _PREAMBLE_LEN + _PURGE_GAP
    filler_index = pd.date_range(
        end=target.index[0] - pd.Timedelta(hours=1), periods=filler_n, freq="h"
    )
    filler = pd.Series(
        np.random.default_rng(seed).normal(0.0, 1e-6, size=filler_n), index=filler_index
    )
    return pd.concat([filler, target])


def _single_split_config(target_len: int, extra_baselines: list) -> ValidationConfig:
    return ValidationConfig(
        train_window=_PREAMBLE_LEN,
        test_window=target_len,
        step=target_len,
        purge_gap=_PURGE_GAP,
        horizon=_HORIZON,
        extra_baselines=extra_baselines,
    )


class _SyntheticForecast:
    """Looks up a precomputed, calibrated forecast for the split's test
    window by index rather than fitting a model. Structurally satisfies the
    `Baseline` protocol.
    """

    def __init__(self, y_pred: pd.Series) -> None:
        self._y_pred = y_pred

    def predict(self, train: pd.Series, test: pd.Series) -> pd.Series:
        return self._y_pred.loc[test.index]


class _SyntheticOLS(_SyntheticForecast):
    pass


class _SyntheticRF(_SyntheticForecast):
    pass


def _assert_naive0(baseline_results) -> None:
    m = baseline_results[NAIVE0_KEY].metrics
    assert m.mae == pytest.approx(NAIVE0_MAE_24H, abs=TOLERANCE)


def _calibrated_magnitude_mean_only(seed: int, target_mean: float) -> np.ndarray:
    """Non-negative array whose mean exactly equals `target_mean`. See
    test_regression_6h.py's identical helper for the full rationale (no
    RMSE published at this horizon, so only a one-parameter rescale is
    solved, not `fixtures._calibrated_magnitudes`'s two-parameter one).
    """
    rng = np.random.default_rng(seed)
    x = rng.gamma(shape=_GAMMA_SHAPE, scale=1.0, size=_N)
    magnitudes = x * (target_mean / x.mean())
    assert magnitudes.min() >= 0, "calibration produced a negative magnitude"
    return magnitudes


def _build_model_mae_scenario(
    seed_true_magnitude: int,
    seed_true_sign: int,
    seed_resid_magnitude: int,
    seed_resid_sign: int,
    model_mae: float,
    index: pd.DatetimeIndex,
) -> tuple[pd.Series, pd.Series]:
    true_magnitude = _calibrated_magnitude_mean_only(seed_true_magnitude, NAIVE0_MAE_24H)
    y_true = pd.Series(
        fixtures._signed(true_magnitude, seed_true_sign), index=index, name="y_true"
    )
    resid_magnitude = _calibrated_magnitude_mean_only(seed_resid_magnitude, model_mae)
    resid = pd.Series(fixtures._signed(resid_magnitude, seed_resid_sign), index=index)
    y_pred = (y_true - resid).rename("y_pred")
    return y_true, y_pred


# ---------------------------------------------------------------------------
# Naive0 / OLS MAE.


def test_naive0_and_ols_mae_end_to_end():
    index = pd.date_range("2022-08-01", periods=_N, freq="h", name="timestamp")
    y_true, y_pred = _build_model_mae_scenario(
        seed_true_magnitude=24001,
        seed_true_sign=24002,
        seed_resid_magnitude=24003,
        seed_resid_sign=24004,
        model_mae=OLS_MAE_24H,
        index=index,
    )
    series = _with_preamble(y_true, seed=24010)
    baseline = _SyntheticOLS(y_pred)
    config = _single_split_config(len(y_true), [baseline])

    results = run_validation_protocol(series, config)

    assert len(results) == 1
    baseline_results = results[0].baseline_results
    _assert_naive0(baseline_results)
    ols_metrics = baseline_results["_SyntheticOLS"].metrics
    assert ols_metrics.mae == pytest.approx(OLS_MAE_24H, abs=TOLERANCE)


# ---------------------------------------------------------------------------
# OLS DA / F1 -- no shared 24h directional fixture exists in fixtures.py, so
# this builds its own quadrant-count scenario via fixtures._build_directional_
# scenario (generic, reused as-is), same technique fixtures.py itself uses
# for 1h/6h.


def test_ols_da_f1_end_to_end():
    scenario = fixtures._build_directional_scenario(
        _OLS_DIR_COUNTS_24H, seed_shuffle=24510, seed_true_magnitude=24511, seed_pred_magnitude=24512
    )
    series = _with_preamble(scenario.y_true, seed=24020)
    baseline = _SyntheticOLS(scenario.y_pred_ols)
    config = _single_split_config(len(scenario.y_true), [baseline])

    results = run_validation_protocol(series, config)

    assert len(results) == 1
    ols_metrics = results[0].baseline_results["_SyntheticOLS"].metrics
    assert ols_metrics.da == pytest.approx(OLS_DA_24H, abs=DIRECTIONAL_TOLERANCE_DA)
    assert ols_metrics.f1 == pytest.approx(OLS_F1_24H, abs=DIRECTIONAL_TOLERANCE_F1)


# ---------------------------------------------------------------------------
# RF MAE -- new synthetic scenario (no prior RF fixture existed for 24h).


def test_rf_mae_end_to_end():
    index = pd.date_range("2022-09-01", periods=_N, freq="h", name="timestamp")
    y_true, y_pred = _build_model_mae_scenario(
        seed_true_magnitude=24101,
        seed_true_sign=24102,
        seed_resid_magnitude=24103,
        seed_resid_sign=24104,
        model_mae=RF_MAE_24H,
        index=index,
    )
    series = _with_preamble(y_true, seed=24110)
    baseline = _SyntheticRF(y_pred)
    config = _single_split_config(len(y_true), [baseline])

    results = run_validation_protocol(series, config)

    assert len(results) == 1
    baseline_results = results[0].baseline_results
    _assert_naive0(baseline_results)
    rf_metrics = baseline_results["_SyntheticRF"].metrics
    assert rf_metrics.mae == pytest.approx(RF_MAE_24H, abs=TOLERANCE)


def test_rf_da_f1_end_to_end():
    scenario = fixtures._build_directional_scenario(
        _RF_DIR_COUNTS_24H, seed_shuffle=24610, seed_true_magnitude=24611, seed_pred_magnitude=24612
    )
    series = _with_preamble(scenario.y_true, seed=24120)
    baseline = _SyntheticRF(scenario.y_pred_ols)  # field name is generic; holds the RF forecast here
    config = _single_split_config(len(scenario.y_true), [baseline])

    results = run_validation_protocol(series, config)

    assert len(results) == 1
    rf_metrics = results[0].baseline_results["_SyntheticRF"].metrics
    assert rf_metrics.da == pytest.approx(RF_DA_24H, abs=DIRECTIONAL_TOLERANCE_DA)
    assert rf_metrics.f1 == pytest.approx(RF_F1_24H, abs=DIRECTIONAL_TOLERANCE_F1)


# ---------------------------------------------------------------------------
# OLS DM verdict count (published 14 better / 22 worse) -- 36 synthetic
# per-split (Naive0, OLS) error pairs, replayed through the real
# splitter/baseline/DM pipeline (horizon=24), same plumbing as
# test_regression_6h.py's test_ols_dm_end_to_end, mixing K<1 ("better") and
# K>1 ("worse") splits to match the published mixed count.
#
# No RMSE is published at 24h (disclosure point 2), so the per-split error
# scale uses NAIVE0_MAE_24H directly -- an order-of-magnitude-appropriate
# spread, not a claim of reproducing any RMSE figure. This fixture verifies
# DM verdict counts only; MAE reproduction is handled separately above.

_DM_SPLIT_N = 500
_DM_SPLIT_NOISE_FRACTION = 0.05
_OLS_DM_KS_24H = [0.98] * 14 + [1.02] * 22  # published: 14 better / 22 worse
_OLS_DM_SEED_BASE_24H = 24100


def _build_dm_splits(ks: list[float], seed_base: int) -> list[fixtures.DMSplitErrors]:
    splits = []
    for i, k in enumerate(ks):
        rng = np.random.default_rng(seed_base + i)
        errors_naive0 = rng.normal(0.0, NAIVE0_MAE_24H, size=_DM_SPLIT_N)
        noise = rng.normal(0.0, _DM_SPLIT_NOISE_FRACTION * NAIVE0_MAE_24H, size=_DM_SPLIT_N)
        errors_model = k * errors_naive0 + noise
        index = pd.RangeIndex(_DM_SPLIT_N, name="point")
        splits.append(
            fixtures.DMSplitErrors(
                errors_naive0=pd.Series(errors_naive0, index=index, name="errors_naive0"),
                errors_model=pd.Series(errors_model, index=index, name="errors_model"),
            )
        )
    return splits


def _build_dm_series(ks: list[float], seed_base: int, seed_filler: int) -> tuple[pd.Series, pd.Series]:
    chunks = _build_dm_splits(ks, seed_base)
    test_w = _DM_SPLIT_N
    step = _PREAMBLE_LEN + _PURGE_GAP + test_w
    total_n = (len(chunks) - 1) * step + _PREAMBLE_LEN + _PURGE_GAP + test_w

    index = pd.date_range("2020-01-01", periods=total_n, freq="h")
    y_true = pd.Series(
        np.random.default_rng(seed_filler).normal(0.0, 1e-6, size=total_n), index=index
    )
    y_pred = y_true.copy()

    for k, chunk in enumerate(chunks):
        test_start_pos = k * step + _PREAMBLE_LEN + _PURGE_GAP
        idx_slice = index[test_start_pos : test_start_pos + test_w]
        # Naive0's forecast is always exactly 0, so errors_naive0 IS y_true on
        # this slice; y_pred is back-derived so that test - y_pred reproduces
        # errors_model exactly once the orchestrator recomputes it.
        errors_naive0 = chunk.errors_naive0.to_numpy()
        errors_model = chunk.errors_model.to_numpy()
        y_true.loc[idx_slice] = errors_naive0
        y_pred.loc[idx_slice] = errors_naive0 - errors_model

    return y_true, y_pred


def test_ols_dm_end_to_end():
    y_true, y_pred = _build_dm_series(_OLS_DM_KS_24H, _OLS_DM_SEED_BASE_24H, seed_filler=24200)
    test_w = _DM_SPLIT_N
    step = _PREAMBLE_LEN + _PURGE_GAP + test_w
    config = ValidationConfig(
        train_window=_PREAMBLE_LEN,
        test_window=test_w,
        step=step,
        purge_gap=_PURGE_GAP,
        horizon=_HORIZON,
        extra_baselines=[_SyntheticOLS(y_pred)],
    )

    results = run_validation_protocol(y_true, config)

    assert len(results) == len(_OLS_DM_KS_24H) == 36
    verdicts = [r.baseline_results["_SyntheticOLS"].dm_result.verdict for r in results]
    assert verdicts.count("better") == 14
    assert verdicts.count("worse") == 22  # published: 14 better / 22 worse


# ---------------------------------------------------------------------------
# Harvey correction demonstration (the acceptance-critical part of this
# ticket) -- see test_regression_6h.py's identical section for the full
# rationale on why an AR(1) construction guarantees genuine, non-trivial
# positive autocorrelation in the loss differential d_t = errors_model_t**2
# - errors_naive0_t**2 (i.i.d. draws, as used in the DM-verdict fixture
# above, would NOT exercise this -- gamma_k ~ 0 for all k>0 there).


def _ar1_errors(n: int, phi: float, sigma: float, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    eps = rng.normal(0.0, sigma, size=n)
    e = np.empty(n)
    e[0] = eps[0]
    for t in range(1, n):
        e[t] = phi * e[t - 1] + eps[t]
    return e


def test_harvey_correction_changes_statistic_at_24h():
    errors_naive0 = _ar1_errors(n=300, phi=0.7, sigma=0.01, seed=778)
    noise = np.random.default_rng(779).normal(0.0, 0.0005, size=300)
    errors_model = 1.15 * errors_naive0 + noise

    result_h1 = dm_test_module.dm_test(errors_model, errors_naive0, horizon=1)
    result_h24 = dm_test_module.dm_test(errors_model, errors_naive0, horizon=_HORIZON)

    # Not just "different" within float noise -- the AR(1) autocorrelation
    # makes the Harvey correction move the statistic by a large, real
    # amount (empirically ~4.0 here), not a few ULPs.
    assert result_h24.statistic != pytest.approx(result_h1.statistic, abs=1e-3)
    assert abs(result_h24.statistic - result_h1.statistic) > 1.0
