"""create validation schema

Revision ID: 0001
Revises:
Create Date: 2026-08-07 11:46:37.414158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('purge_gap_hours', sa.Float(), nullable=False),
    sa.Column('split_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('split_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('split_index', sa.Integer(), nullable=False),
    sa.Column('train_start', sa.DateTime(), nullable=False),
    sa.Column('train_end', sa.DateTime(), nullable=False),
    sa.Column('purge_start', sa.DateTime(), nullable=True),
    sa.Column('purge_end', sa.DateTime(), nullable=True),
    sa.Column('test_start', sa.DateTime(), nullable=False),
    sa.Column('test_end', sa.DateTime(), nullable=False),
    sa.Column('model_mae', sa.Float(), nullable=False),
    sa.Column('model_rmse', sa.Float(), nullable=False),
    sa.Column('model_smape', sa.Float(), nullable=False),
    sa.Column('model_mase', sa.Float(), nullable=False),
    sa.Column('model_da', sa.Float(), nullable=False),
    sa.Column('model_f1', sa.Float(), nullable=False),
    sa.Column('model_oos_r2', sa.Float(), nullable=False),
    sa.Column('naive0_mae', sa.Float(), nullable=False),
    sa.Column('naive0_rmse', sa.Float(), nullable=False),
    sa.Column('naive0_smape', sa.Float(), nullable=False),
    sa.Column('naive0_mase', sa.Float(), nullable=False),
    sa.Column('naive0_da', sa.Float(), nullable=False),
    sa.Column('naive0_f1', sa.Float(), nullable=False),
    sa.Column('naive0_oos_r2', sa.Float(), nullable=False),
    sa.Column('dm_statistic', sa.Float(), nullable=False),
    sa.Column('dm_pvalue', sa.Float(), nullable=False),
    sa.Column('dm_verdict', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('split_results')
    op.drop_table('runs')
    # ### end Alembic commands ###
